version: 0.0
os: linux

files:
  - source: project.html
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: project.html
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/webserver-stop.sh
  AfterInstall:
    - location: scripts/webserver-start.sh
